name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: check-out code
      uses: actions/checkout@v3
      
    - name: Super-Linter
      uses: github/super-linter@v4.10.1      

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    ## Build and Publishes our image to Docker Hub 😎
    - name: Docker Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: marcomeulenbroeks/helloapp:latest
