name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: check-out code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    ## Build and Publishes our image to Docker Hub 😎
    - name: Docker Build and Push
      uses: docker/build-and-push-action@v2
      with:
        context .
        push: true
        tags: nlehvmema/helloapp:latest