name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    ## Builds our docker image!
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nlehvmema/helloapp
    ## Publishes our image to Docker Hub 😎
    - name: Docker Push
      run: docker push nlehvmema/helloapp